name: OCaml CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Setup OCaml
      uses: avsm/setup-ocaml@v2
      with:
        ocaml-version: '5.1.0'
    - name: test environment
      run: make test_environment && ./tests/test_environment
    - name: test expression
      run: make test_expression && ./tests/test_expression
