name: OCaml CI

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: test environment
      run: make test_environment && ./tests/test_environment
    - name: test expression
      run: make test_expression && ./tests/test_expression
    - name: test parse and run
      run: make test_parse_and_run && ./tests/test_parse_and_run
    - name: test function
      run: make test_function && ./tests/test_function
    - name: test recursive function
      run: make test_recursive_function && ./tests/test_recursive_function
    - name: test type error
      run: make test_type_err && ./tests/test_type_err
    - name: test list
      run: make test_list && ./tests/test_list
    - name: test type checker
      run: make test_type_checker && ./tests/test_type_checker
